[package]
name = "vvenc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libvvenc-sys = { path = "libvvenc-sys", version = "0.1.0" }
thiserror = "1.0.37"

[workspace]
members = ["vvencli"]
