[package]
name = "vvencli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vvenc = { path = "..", version = "0.0.1" }
y4m = "0.8"
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
